version: 2

sources:
    - name: staging
      # database: taxi-rides-ny-339813
      database: de-zoomcamp-prj-375800
      schema: trips_data_all

      tables:
        - name: green_tripdata
        - name: yellow_tripdata